# ---------------------------------------------  启动端口 ------------------------------------------------------- #
server:
  port: 8080

spring:
# ---------------------------------------------  数据库配置(默认使用mysql：5.5+) -----------------------------------#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 10MB

  # ---------------------------------------------  配置 JPA ------------------------------------------------------- #
  jpa:
    hibernate:
# ---------------------------------------------  更新策略 ------------------------------------------------------- #
      ddl-auto: update
# ---------------------------------------------  打印SQL ------------------------------------------------------- #
    show-sql: true
# ---------------------------------------------  自动生成表结构 ------------------------------------------------- #
    generate-ddl: true

  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/


  devtools:
    restart:
      enabled: true
      additional-paths: src/java/main
      exclude: static/**,public/**,WEB-INF/**

# --------------------------------------------- 配置mybatis ---------------------------------------------------- #
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# ---------------------------------------------文件上传 --------------------------------------------------------- #
file:
  path: c://images/
  relative: /images/**
